# Generated by Django 4.1.3 on 2023-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('tag', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Search_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('tags', models.TextField()),
                ('search_amount', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
