# Generated by Django 4.1.3 on 2023-09-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_data',
            name='photo_id',
            field=models.CharField(default=19999, max_length=10),
            preserve_default=False,
        ),
    ]
