# Generated by Django 4.1.3 on 2023-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_search_data_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='photo_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
